version: '3.8'

services:
  book_service:
    build:
      context: .
      dockerfile: Dockerfile.book
    ports:
      - "8000:8000"

  rating_service:
    build:
      context: .
      dockerfile: Dockerfile.rating
    ports:
      - "8001:8001"

  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8002:8002"
    depends_on:
      - book_service
      - rating_service